export const metadata = {
  title: 'About page',
  description: 'Generated by create next app',
  // authors: 'myName',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="">
        the navbar layout
        {children}
      </div>
    </>
  );
}
